---
title: "Single Cell University"
output: github_document
---

Single-cell is a rapid and exciting evolving field. There is a lot of resources and classes and slides scattered online but it is hard for someone just starting to collect their thoughts and follow a guide that can help them start their single-cell learning path.

The idea of this repository is to act as a tentative curriculum that encompasses different areas where single-cell can serve as an important tool for scientific discovery. The intention is not to collect every single tutorial in existence but aggregate the best resources that can give a comprehensive overview of the field.

PRs are extremely welcomed, together we can make a comprehensive and dynamic evolving curriculum for single-cell. I tried my best to give credits to authors of the tutorials/videos/slides, if you find anything incorrectly or would like to have it removed from this repository please let me know and it'll be quickly fixed.

Some of the fields haven't yet developed dedicated workshops/classes so they will be presented as tutorials of specific tools that are available.

This repository was largely inspired by awesome initiatives such as [OSSU](https://github.com/ossu/bioinformatics) and [Awesome Single-Cell](https://github.com/seandavi/awesome-single-cell), go check them out.


# Curriculum



## Biology



## Single-cell history


## scDNA

##### Mutation Calling

##### Copy Number
 
## scRNA

scRNA is the most extensive documented area with a plethora of tutorials. 

##### Reference Book
| Link   | Authors   | Publication |
|---|---|---|
| [Orchestrating Single-Cell Analysis](Orchestrating Single-Cell Analysis)  | [Bioconductor](https://osca.bioconductor.org/contributors.html)   | [Reference](https://www.nature.com/articles/s41592-019-0654-x) |

##### Classes
| Topic | Author | References  |
|---|---|---|
| **Pre-Processing** |  |  
| **Normalization**  |  |  
| **Feature Selection**  |  | 
| **Dimensionality Reduction**  |  |
| **Clustering**  |  |
| **Cell Annotation**  |  | 
| **Pseudotime**  |  |
| **RNA Velocity**  |  |

## scATAC


## Integrating data



## Flow Cytometry


